name: pipeline
on:
  [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install openjdk-17-jdk build-essential
      - name: Build
        run: |
          mkdir -p build
          javac -sourcepath src -d build src/NinB.java
