name: pipeline
on:
  pull_request:
    types: [opened, edited, synchronize, reopened, labeled]
  push:
    branches:
      - master
      - hw02
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Build
        run: |
          cd hw1
          ./gradlew compileJava
      - name: Test
        run: |
          cd hw1
          ./gradlew test
